### ISSUE TITLE
Python 3.12 support without

### ISSUE THREAD

**Issue by vhiairrassary** [axiomhq/axiom-cloudwatch-forwarder#72]
When used with Python 3.12 we can see a lot of warnings, such as:
```
/var/task/index.py:20: SyntaxWarning: invalid escape sequence '\d'
std_matcher = re.compile("\d\d\d\d-\d\d-\d\d\S+\s+(?P<requestID>\S+)")
```

This is not urgent as there is no EOL planned by AWS for the `python3.9` runtime yet

**Comment by schehata** [comment]
hey @vhiairrassary can you try the new version, I think the problem should be solved since I switched to raw strings.
